import Head from 'next/head'
import { Inter } from 'next/font/google'
import Profile from '@/components/profile'
import ProjectPreview from '@/components/project_preview'
import Skills from '@/components/skills'
import Contact from '@/components/contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='text-slate-950 flex'>
      <Head>
        <title>{`garrettheiner.dev`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-4xl m-auto flex flex-col gap-4 p-4 -translate-y-10'>
        <Profile />
        <Skills />
        <ProjectPreview />
        <Contact />
      </main>
    </div>
  )
}
