import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Profile from '@/components/profile'
import ProjectPreview from '@/components/project_preview'
import Skills from '@/components/skills'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='text-slate-700 flex '>
      <Head>
        <title>{`Garrett.dev`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-xl m-auto flex flex-col gap-4'>
        <Profile />
        <Skills />
        <ProjectPreview />
      </main>
    </div>
  )
}
